# Generated by Django 4.0.1 on 2022-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='14/01/2022', max_length=30, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
