# Generated by Django 4.0.1 on 2022-01-15 09:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип доставки',
            },
        ),
        migrations.CreateModel(
            name='DestinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип назначения',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255, verbose_name='от куда')),
                ('to_location', models.CharField(max_length=255, verbose_name='куда')),
                ('dictance_between', models.CharField(max_length=255, verbose_name='дистанция')),
            ],
            options={
                'verbose_name': 'Направление',
            },
        ),
        migrations.CreateModel(
            name='ParcelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='масса')),
                ('hight', models.FloatField(verbose_name='высота')),
                ('lenght', models.FloatField(verbose_name='длина')),
                ('width', models.FloatField(verbose_name='ширина')),
                ('volume', models.FloatField(verbose_name='объем')),
            ],
            options={
                'verbose_name': 'Информация о посылке',
            },
        ),
        migrations.CreateModel(
            name='ParcelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('хрупкий', 'хрупкий')], max_length=255)),
            ],
            options={
                'verbose_name': 'Варианты посылок',
            },
        ),
        migrations.CreateModel(
            name='ParcelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('доставлено', 'доставлено'), ('обработке', 'обработке'), ('В пути', 'В пути')], max_length=20)),
            ],
            options={
                'verbose_name': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mbank', 'Мбанк'), ('cash', 'Наличка')], default='cash', max_length=20)),
            ],
            options={
                'verbose_name': 'Тип оплата',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Называние')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('create_at', models.DateField(default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pay_satus', models.CharField(choices=[('paid', 'Оплачено'), ('not paid', 'Не оплачено')], max_length=25, verbose_name='статус оплаты')),
                ('recipient_info', models.CharField(max_length=255, verbose_name='Получатель')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.deliverytype', verbose_name='тип доставки')),
                ('destination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.destinationtype', verbose_name='тип назначения')),
                ('location_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.direction', verbose_name='направления')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.parceloption', verbose_name='варианты посылок')),
                ('parsel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.parcelinfo', verbose_name='информация о посылке')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.paymenttype', verbose_name='способ оплаты')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('sender_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.userinfo', verbose_name='данных отправителя')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.parcelstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Посылка',
            },
        ),
    ]
