# Generated by Django 4.0.1 on 2022-01-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='pay_satus',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('not paid', 'Не оплачено')], max_length=25, verbose_name='статус оплаты'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='parceloption',
            name='name',
            field=models.CharField(choices=[('хрупкий', 'хрупкий')], max_length=255),
        ),
    ]
