from django.contrib import admin

from account.models import User
from .models import (
    Parcel,
    Town,
    Area,
    UserInfo,
    ParcelOption,
    PaymentType,
    ParcelInfo,
    Recipient,
    ParcelStatus,
    DeliveryType,
    Envelope,
    Directions,
    Direction,
    )
admin.site.register(Town),
admin.site.register(Area),
admin.site.register(ParcelOption),
admin.site.register(Parcel),
admin.site.register(UserInfo),
admin.site.register(Recipient),
admin.site.register(PaymentType),
admin.site.register(ParcelInfo),
admin.site.register(ParcelStatus),
admin.site.register(DeliveryType),
admin.site.register(Envelope),
admin.site.register(Directions),
admin.site.register(Direction),
